// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List hosts (optionally fuzzy/prefix-filtered by core's matcher), sorted by
 * name. Reloads from disk first so TUI edits show up live.
 */
async listHosts(filter: string | null) : Promise<Host[]> {
    return await TAURI_INVOKE("list_hosts", { filter });
},
async listFolders() : Promise<string[]> {
    return await TAURI_INVOKE("list_folders");
},
async getHost(name: string) : Promise<Host | null> {
    return await TAURI_INVOKE("get_host", { name });
},
/**
 * Create or update a host. When `original_name` differs from `host.name` the
 * old key is removed (a rename). Writes `host.json` and re-exports.
 */
async saveHost(host: Host, originalName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_host", { host, originalName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHost(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_host", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloneHost(name: string, newName: string) : Promise<Result<Host, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_host", { name, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFolder(oldName: string, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_folder", { oldName, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a folder. When `delete_hosts` is true its hosts go too; otherwise
 * they're moved to the top level (folder cleared).
 */
async deleteFolder(name: string, deleteHosts: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { name, deleteHosts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open an ssh session to `name` in a new external terminal window, honoring
 * `external_terminal` from settings. Never embeds ssh in the webview.
 */
async connectHost(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_host", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Probe every host's reachability (concurrent TCP connect to `host:port`).
 * Hosts behind a ProxyJump are skipped (reported as `None`) since their
 * address usually isn't directly reachable.
 */
async pingHosts() : Promise<Result<HostPing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inspect a host's SSH key: the fingerprint pinned in `~/.ssh/known_hosts`
 * alongside the one the server presents right now (`ssh-keyscan`), plus a
 * verdict (unpinned / match / changed / unreachable). Mirrors the TUI's `F`
 * inspector. The live scan is a network round-trip (~5s worst case).
 */
async hostKeyInfo(name: string) : Promise<Result<HostKeyInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("host_key_info", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trust-on-first-use: fetch the host's live key and pin it in `known_hosts`.
 * The caller is expected to have shown the fingerprint and gotten consent.
 */
async pinHostKey(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pin_host_key", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget a host's pinned key (`ssh-keygen -R`, including the `[host]:port`
 * form for non-default ports).
 */
async forgetHostKey(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_host_key", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recover from a changed host key: forget the stale entry, then pin the key the
 * server presents now. Fails (leaving nothing pinned) if the host is
 * unreachable, so the user can retry rather than end up trusting nothing.
 */
async replaceHostKey(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_host_key", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppConfig> {
    return await TAURI_INVOKE("get_settings");
},
async saveSettings(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIdentities() : Promise<IdentityDto[]> {
    return await TAURI_INVOKE("list_identities");
},
async generateIdentity(keyType: string, name: string, comment: string, passphrase: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_identity", { keyType, name, comment, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentAddIdentity(privatePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_add_identity", { privatePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentRemoveIdentity(privatePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_remove_identity", { privatePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push a public key to a host's `authorized_keys`. `pub_path` overrides the
 * key; otherwise the host's identity `.pub` (or a default) is used.
 */
async pushPubkey(hostName: string, pubPath: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_pubkey", { hostName, pubPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterOverview() : Promise<KlusterOverview> {
    return await TAURI_INVOKE("kluster_overview");
},
/**
 * Add a Kubernetes/K3s cluster to `kluster.json`. Rejects a duplicate name.
 */
async klusterAddCluster(cluster: Cluster) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_add_cluster", { cluster }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the cluster named `original_name` in place. Allows renaming, but
 * rejects a rename that collides with another existing cluster.
 */
async klusterUpdateCluster(originalName: string, cluster: Cluster) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_update_cluster", { originalName, cluster }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the cluster named `name` from `kluster.json`.
 */
async klusterDeleteCluster(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_delete_cluster", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a saved SSH host as a remote Docker daemon (`DOCKER_HOST=ssh://…`).
 */
async klusterAddDockerRemote(hostAlias: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_add_docker_remote", { hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop tracking a Docker remote (the remote daemon itself is untouched).
 */
async klusterDeleteDockerRemote(hostAlias: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_delete_docker_remote", { hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Context names discovered across `~/.kube/config` + `$KUBECONFIG`, for the
 * add-cluster form's suggestions. Best-effort — empty when none are readable.
 */
async klusterKubeContexts() : Promise<string[]> {
    return await TAURI_INVOKE("kluster_kube_contexts");
},
async klusterDockerContainers(hostAlias: string | null) : Promise<Result<ContainerInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_containers", { hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterPods(cluster: Cluster) : Promise<Result<PodInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_pods", { cluster }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterIncus(remote: string | null) : Promise<Result<IncusInstance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_incus", { remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterDockerLifecycle(id: string, action: LifecycleAction, hostAlias: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_lifecycle", { id, action, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterIncusLifecycle(name: string, action: LifecycleAction, remote: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_incus_lifecycle", { name, action, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into a Docker container as an embedded terminal session.
 * Returns the session id.
 */
async klusterDockerShell(id: string, hostAlias: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_shell", { id, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tail a Docker container's logs as an embedded terminal session.
 */
async klusterDockerLogs(id: string, hostAlias: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_logs", { id, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The rich `inspect`-backed detail view for a Docker container (local or,
 * with `host_alias`, a remote daemon over SSH).
 */
async klusterDockerInspect(id: string, hostAlias: string | null) : Promise<Result<ContainerDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_inspect", { id, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterAppleContainers() : Promise<Result<ContainerInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_apple_containers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterAppleLifecycle(id: string, action: LifecycleAction) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_apple_lifecycle", { id, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The rich `inspect`-backed detail view for an Apple container.
 */
async klusterAppleInspect(id: string) : Promise<Result<ContainerDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_apple_inspect", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into an Apple container as an embedded terminal session.
 */
async klusterAppleShell(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_apple_shell", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tail an Apple container's logs as an embedded terminal session.
 */
async klusterAppleLogs(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_apple_logs", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into a k8s pod as an embedded terminal session.
 */
async klusterPodShell(cluster: Cluster, namespace: string, pod: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_pod_shell", { cluster, namespace, pod }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into an Incus instance as an embedded terminal session.
 */
async klusterIncusShell(name: string, remote: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_incus_shell", { name, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every background tunnel across all sshm instances (fed by the shared
 * `tunnels/<pid>.json` files), plus a reap of this app's dead children.
 */
async listTunnels() : Promise<TunnelRecord[]> {
    return await TAURI_INVOKE("list_tunnels");
},
/**
 * Saved (persisted) tunnels defined on a host.
 */
async hostTunnels(name: string) : Promise<Tunnel[]> {
    return await TAURI_INVOKE("host_tunnels", { name });
},
/**
 * Start the host's saved tunnel at `index` as a background `ssh -N`.
 */
async startTunnel(hostName: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_tunnel", { hostName, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a background tunnel this app started, by pid.
 */
async stopTunnel(pid: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_tunnel", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force a reload of the DB from disk (e.g. after a live-sync event) and return
 * the fresh host list.
 */
async reloadDb() : Promise<Host[]> {
    return await TAURI_INVOKE("reload_db");
},
/**
 * Open an embedded ssh session to `host_name`. Returns the session id; output
 * then arrives as `TermOutputEvent`s carrying that id. Mosh is rejected (it
 * stays external-terminal only).
 */
async termOpen(hostName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_open", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a local shell (the user's `$SHELL`, else `/bin/sh`) in the app.
 */
async termOpenLocal() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_open_local") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termWrite(id: string, data: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_write", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termResize(id: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_resize", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termClose(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_close", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dbChangedEvent: DbChangedEvent,
pathReadyEvent: PathReadyEvent,
termExitEvent: TermExitEvent,
termOutputEvent: TermOutputEvent
}>({
dbChangedEvent: "db-changed-event",
pathReadyEvent: "path-ready-event",
termExitEvent: "term-exit-event",
termOutputEvent: "term-output-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppConfig = { default_port?: number; default_username?: string; default_identity_file?: string; export_path?: string; 
/**
 * Auto-refresh reachability/latency for every host in the background.
 * Enabled by default; user can turn it off from the Settings tab.
 */
auto_health_check?: boolean; 
/**
 * Pause the background health worker while an interactive SSH session
 * is in the foreground, and resume it on return. Avoids the network
 * noise of probing every host while you're actually working on one.
 * Enabled by default; toggle from the Settings tab.
 */
pause_health_on_session?: boolean; 
/**
 * How often (seconds) the background worker re-probes every host.
 * Doubles as the cache TTL — entries older than this are re-probed.
 */
health_ttl_secs?: number; 
/**
 * TCP connect timeout (ms) used by each probe. SSH banner read is
 * derived from this (~1/3, capped at 750ms).
 */
health_probe_timeout_ms?: number; 
/**
 * How often (seconds) the Kluster tab refreshes the docker container
 * list and the pods of every saved cluster.
 */
kluster_refresh_secs?: number; 
/**
 * Default `--tail N` for `docker logs` / `kubectl logs` from the
 * Kluster tab.
 */
kluster_log_tail_lines?: number; 
/**
 * Command prefix used to open an SSH session in a new terminal window
 * (the `o` hotkey). Empty = auto-detect. Example: `kitty -e`,
 * `wezterm start --`, `gnome-terminal --`, `alacritty -e`.
 */
external_terminal?: string; 
/**
 * Emit native desktop notifications (tunnel dropped, host up/down).
 * Enabled by default; toggle from the Settings tab.
 */
notifications_enabled?: boolean; 
/**
 * Custom icon for desktop notifications (path, `~` allowed). Empty = OS
 * default. On macOS this needs `terminal-notifier` installed — plain
 * `osascript` can't override the notification icon.
 */
notification_icon?: string; 
/**
 * Git-backed configuration sync. **Must stay the last field**: it
 * serializes as a `[sync]` TOML table, and anything declared after it
 * would end up nested inside that table.
 */
sync?: SyncConfig }
/**
 * One saved cluster entry. `kubeconfig` and `context` are both optional;
 * when omitted, `kubectl` is invoked with no `--kubeconfig`/`--context`
 * flags and falls back to the standard env / `current-context` rules.
 */
export type Cluster = { name: string; kind?: ClusterKind; kubeconfig?: string | null; context?: string | null; namespace_default?: string | null }
/**
 * Display flavour for a saved cluster — purely cosmetic, drives the badge in
 * the tab. Detection is naïve (substring on context name), users can toggle.
 */
export type ClusterKind = "K8s" | "K3s"
/**
 * What to do when the same file changed on both sides since the last sync.
 */
export type ConflictPolicy = 
/**
 * Merge what can be merged (host/cluster entries), and keep **this**
 * machine's version of anything that truly collides. The default.
 */
"prefer_local" | 
/**
 * Same merge, but a true collision resolves to the remote version.
 */
"prefer_remote"
/**
 * Parsed, runtime-agnostic detail for one container/instance, built from an
 * `inspect` call. Rendered by the Kluster detail popup.
 */
export type ContainerDetail = { 
/**
 * Header line (usually the container name).
 */
title: string; sections: DetailSection[]; 
/**
 * Last few log lines, when the runtime could produce them cheaply.
 */
log_tail: string[] }
/**
 * Snapshot of one Docker container at the moment of `docker ps`.
 */
export type ContainerInfo = { id: string; name: string; image: string; status: string; running: boolean }
/**
 * Emitted when a shared config file changes on disk (from this app, the TUI,
 * another GUI instance, or a text editor). The frontend refreshes whichever
 * view the flags indicate. Backed by `sshm_core::watch`.
 */
export type DbChangedEvent = { hosts: boolean; kluster: boolean; settings: boolean }
/**
 * One titled group of label→value rows in the rich detail view (e.g.
 * "Networking" holding `IPv4 → 192.168.64.3`). Purely presentational.
 */
export type DetailSection = { title: string; rows: ([string, string])[] }
/**
 * A reference to a remote Docker daemon reached over SSH. The actual
 * connection details are looked up from the saved Host map (`host.json`)
 * at runtime, so renaming/editing the SSH host's user/port flows through.
 */
export type DockerRemote = { 
/**
 * Name of an entry in the SSH Host DB (`Host.name`).
 */
host_alias: string }
/**
 * Représente une entrée d'hôte SSH (schéma v2).
 */
export type Host = { 
/**
 * Alias (clé logique)
 */
name: string; 
/**
 * Hostname ou IP (ex `1.2.3.4` ou `example.com`)
 */
host: string; 
/**
 * Port SSH (par défaut 22)
 */
port?: number; 
/**
 * Nom d'utilisateur SSH
 */
username?: string; 
/**
 * Chemin vers la clé privée (ex: ~/.ssh/id_ed25519)
 */
identity_file?: string | null; 
/**
 * ProxyJump éventuel. Peut être une chaîne multi-hop séparée par des virgules
 * (ex: "bastion1,bastion2"). Chaque entrée peut être un nom d'hôte sauvegardé
 * dans sshm — il sera alors résolu en `user@host:port` au lancement.
 */
proxy_jump?: string | null; 
/**
 * Tags pour filtrage/organisation
 */
tags?: string[] | null; 
/**
 * Folder logique (ex : "Production", "Staging", etc.)
 * Peut être None (pas de dossier)
 */
folder?: string | null; 
/**
 * Timestamp RFC3339 UTC de la dernière connexion réussie.
 */
last_connected_at?: string | null; 
/**
 * Nombre total de connexions depuis ce gestionnaire.
 */
use_count?: number; 
/**
 * Marqueur "favori" (affiché en tête de liste via tri dédié).
 */
favorite?: boolean; 
/**
 * Tunnels persistants associés à cet hôte.
 */
tunnels?: Tunnel[]; 
/**
 * Forward le ssh-agent local (`-A`). Implication de sécurité : permet à un
 * utilisateur root du host distant d'utiliser tes clés. À n'activer que sur
 * des hôtes de confiance (typiquement bastions). Désactivé par défaut.
 */
forward_agent?: boolean; 
/**
 * Connecte via `mosh` plutôt que `ssh`. mosh doit être installé localement
 * et sur l'hôte distant ; le port / l'identité / le ProxyJump sont passés
 * à mosh via `--ssh`. Désactivé par défaut.
 */
mosh?: boolean; 
/**
 * Note libre de l'utilisateur sur cet hôte (affichée dans le panneau de
 * détail). `None` quand aucune note n'a été saisie.
 */
notes?: string | null; 
/**
 * Commande à exécuter automatiquement à la connexion (mappée sur l'option
 * ssh `RemoteCommand`, avec `-t` pour forcer un TTY). Par défaut, la
 * commande est lancée puis on enchaîne sur un shell interactif de login
 * (`; exec $SHELL -l` ajouté automatiquement) — sinon ssh fermerait la
 * session dès la fin de la commande. Si la commande contient `exec `,
 * elle est utilisée telle quelle (l'utilisateur gère le shell lui-même).
 * `None` = shell de login normal. Ignoré en mode mosh.
 */
remote_command?: string | null }
/**
 * One host key (algorithm + SHA256 fingerprint), flattened for the webview.
 */
export type HostKeyDto = { key_type: string; fingerprint: string }
/**
 * The pinned vs. live host key(s) for a saved host, plus the verdict. Feeds the
 * GUI host-key inspector so the user can pin, forget, or replace a stale key.
 */
export type HostKeyInfo = { 
/**
 * The resolved hostname the check ran against.
 */
host: string; port: number; pinned: HostKeyDto[]; live: HostKeyDto[]; status: HostKeyStatus }
/**
 * Verdict when comparing the key pinned in `known_hosts` against the one the
 * server presents right now — mirrors the TUI's `F` inspector.
 */
export type HostKeyStatus = 
/**
 * Reachable, nothing pinned yet — a trust-on-first-use decision.
 */
"Unpinned" | 
/**
 * A key is pinned but the server couldn't be reached to compare.
 */
"Unreachable" | 
/**
 * The pinned key matches what the server presents. All good.
 */
"Match" | 
/**
 * A key is pinned but it does NOT match the server — a changed key.
 */
"Changed" | 
/**
 * No key on either side.
 */
"Unknown"
/**
 * Reachability of a host: `latency_ms = Some(ms)` when a direct TCP connect to
 * `host:port` succeeded, `None` when it couldn't be reached directly (down, or
 * only reachable through a ProxyJump).
 */
export type HostPing = { name: string; latency_ms: number | null }
/**
 * One SSH key under `~/.ssh`, with paths flattened to strings for the webview.
 */
export type IdentityDto = { private: string; public: string; key_type: string; bits: number | null; comment: string; fingerprint: string; in_agent: boolean; is_hardware: boolean }
/**
 * Snapshot of one Incus instance (container or VM).
 */
export type IncusInstance = { name: string; 
/**
 * `container` or `virtual-machine`.
 */
kind: string; 
/**
 * `Running`, `Stopped`, …
 */
status: string; 
/**
 * Image alias / fingerprint, when reported.
 */
image: string; running: boolean }
/**
 * A saved cluster/remote plus which runtime it targets, for the Kluster tab.
 */
export type KlusterOverview = { clusters: Cluster[]; incus_remotes: string[]; docker_remotes: DockerRemote[]; docker_local_available: boolean; 
/**
 * Apple's native `container` runtime (macOS 26+, Apple silicon).
 */
apple_local_available: boolean; incus_local_available: boolean; kube_available: boolean }
/**
 * A start / stop / restart operation on a Docker container or Incus instance.
 */
export type LifecycleAction = "Start" | "Stop" | "Restart"
/**
 * Emitted once the real `PATH` has been recovered from the login shell (done
 * off the main thread so the window opens instantly). Tools like `docker` /
 * `kubectl` / `incus` / `ssh` are only resolvable after this fires, so the
 * frontend defers Kluster discovery until then.
 */
export type PathReadyEvent = null
/**
 * Snapshot of one k8s pod at the moment of `kubectl get pods`.
 */
export type PodInfo = { namespace: string; name: string; containers: string[]; 
/**
 * e.g. `Running`, `Pending`, `CrashLoopBackOff`.
 */
phase: string }
/**
 * Git-backed sync of the sshm config across machines.
 * 
 * Auth is SSH-key based: `repo_url` is an SSH remote (`git@host:owner/repo.git`)
 * and `ssh_key` the private key handed to git through `GIT_SSH_COMMAND`. No
 * credentials are ever written to the repo.
 */
export type SyncConfig = { 
/**
 * Master switch. Off = every automatic trigger is skipped and an explicit
 * `sshm sync` refuses with a hint to run `sshm sync setup`.
 */
enabled?: boolean; 
/**
 * SSH remote, e.g. `git@github.com:me/sshm-config.git`.
 */
repo_url?: string; 
/**
 * Private key passed to `ssh -i`. `~` is expanded. Empty = whatever the
 * user's ssh-agent / `~/.ssh/config` provides.
 */
ssh_key?: string; 
/**
 * Branch to track.
 */
branch?: string; mode?: SyncMode; 
/**
 * Interval used by [`SyncMode::Interval`], in seconds. Floored at 60 by
 * [`SyncConfig::effective_interval`] so a typo can't hammer the remote.
 */
interval_secs?: number; 
/**
 * Sync once, right after the TUI starts.
 */
on_start?: boolean; 
/**
 * Sync once more when leaving the TUI, so local edits land upstream.
 */
on_exit?: boolean; 
/**
 * Files carried by a sync run.
 */
items?: SyncItem[]; conflict?: ConflictPolicy; 
/**
 * Fail instead of trusting an unknown host key. Off by default, which
 * maps to ssh's `StrictHostKeyChecking=accept-new` (trust on first use,
 * refuse on change).
 */
strict_host_key_checking?: boolean }
/**
 * Which shared config file a sync run carries.
 */
export type SyncItem = 
/**
 * `host.json` — hosts, folders, tunnels. Merged entry-by-entry.
 */
"hosts" | 
/**
 * `kluster.json` — saved clusters and Incus remotes.
 */
"kluster" | 
/**
 * `settings.toml` — app settings, minus the `[sync]` table which always
 * stays machine-local (see [`crate::sync`]).
 */
"settings" | 
/**
 * `theme.toml` — colors.
 */
"theme"
/**
 * When an sshm process syncs on its own.
 */
export type SyncMode = 
/**
 * Never automatic: only `sshm sync` (or a cron entry calling it) syncs.
 */
"manual" | 
/**
 * The TUI syncs every `interval_secs` in the background, and
 * `sshm sync --if-due` becomes a no-op until the interval has elapsed.
 */
"interval"
/**
 * The embedded terminal session `id`'s child process exited.
 */
export type TermExitEvent = { id: string }
/**
 * A chunk of output bytes from an embedded terminal session `id`.
 */
export type TermOutputEvent = { id: string; data: number[] }
/**
 * Définition d'un tunnel SSH sauvegardable.
 */
export type Tunnel = { 
/**
 * Libellé court (ex : "Postgres prod").
 */
label?: string; kind?: TunnelKind; 
/**
 * Port côté local (Local/Dynamic) ou côté remote-bind (Remote).
 */
local_port: number; 
/**
 * Port distant cible (Local/Remote). Ignoré pour Dynamic.
 */
remote_port?: number; 
/**
 * Hôte distant cible (Local/Remote). Vide => `localhost` côté remote.
 */
remote_host?: string }
/**
 * Type de tunnel SSH.
 */
export type TunnelKind = 
/**
 * `-L` Local forward: localhost:local_port -> remote:remote_port (via SSH host)
 */
"Local" | 
/**
 * `-R` Remote forward: remote:remote_port -> localhost:local_port
 */
"Remote" | 
/**
 * `-D` Dynamic SOCKS proxy on localhost:local_port
 */
"Dynamic"
/**
 * One running background tunnel, as persisted to a per-instance state file.
 * 
 * The field names here are the shared on-disk contract every frontend reads
 * and writes, so a dashboard in one instance can list another's tunnels.
 * `started` is an RFC3339 timestamp (the TUI serializes a `DateTime<Utc>` to
 * the exact same string, so the two interoperate).
 */
export type TunnelRecord = { 
/**
 * PID of the `ssh -N` process.
 */
pid: number; host_name: string; 
/**
 * `user@host:port`, for display.
 */
host_display: string; tunnel: Tunnel; 
/**
 * RFC3339 start timestamp.
 */
started: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
