// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List hosts (optionally fuzzy/prefix-filtered by core's matcher), sorted by
 * name. Reloads from disk first so TUI edits show up live.
 */
async listHosts(filter: string | null) : Promise<Host[]> {
    return await TAURI_INVOKE("list_hosts", { filter });
},
async listFolders() : Promise<string[]> {
    return await TAURI_INVOKE("list_folders");
},
async getHost(name: string) : Promise<Host | null> {
    return await TAURI_INVOKE("get_host", { name });
},
/**
 * Create or update a host. When `original_name` differs from `host.name` the
 * old key is removed (a rename). Writes `host.json` and re-exports.
 */
async saveHost(host: Host, originalName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_host", { host, originalName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHost(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_host", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloneHost(name: string, newName: string) : Promise<Result<Host, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_host", { name, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFolder(oldName: string, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_folder", { oldName, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a folder. When `delete_hosts` is true its hosts go too; otherwise
 * they're moved to the top level (folder cleared).
 */
async deleteFolder(name: string, deleteHosts: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { name, deleteHosts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open an ssh session to `name` in a new external terminal window, honoring
 * `external_terminal` from settings. Never embeds ssh in the webview.
 */
async connectHost(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_host", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppConfig> {
    return await TAURI_INVOKE("get_settings");
},
async saveSettings(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIdentities() : Promise<IdentityDto[]> {
    return await TAURI_INVOKE("list_identities");
},
async generateIdentity(keyType: string, name: string, comment: string, passphrase: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_identity", { keyType, name, comment, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentAddIdentity(privatePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_add_identity", { privatePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentRemoveIdentity(privatePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_remove_identity", { privatePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push a public key to a host's `authorized_keys`. `pub_path` overrides the
 * key; otherwise the host's identity `.pub` (or a default) is used.
 */
async pushPubkey(hostName: string, pubPath: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_pubkey", { hostName, pubPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterOverview() : Promise<KlusterOverview> {
    return await TAURI_INVOKE("kluster_overview");
},
async klusterDockerContainers(hostAlias: string | null) : Promise<Result<ContainerInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_containers", { hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterPods(cluster: Cluster) : Promise<Result<PodInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_pods", { cluster }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterIncus(remote: string | null) : Promise<Result<IncusInstance[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_incus", { remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterDockerLifecycle(id: string, action: LifecycleAction, hostAlias: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_lifecycle", { id, action, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async klusterIncusLifecycle(name: string, action: LifecycleAction, remote: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_incus_lifecycle", { name, action, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into a Docker container as an embedded terminal session.
 * Returns the session id.
 */
async klusterDockerShell(id: string, hostAlias: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_shell", { id, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tail a Docker container's logs as an embedded terminal session.
 */
async klusterDockerLogs(id: string, hostAlias: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_docker_logs", { id, hostAlias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into a k8s pod as an embedded terminal session.
 */
async klusterPodShell(cluster: Cluster, namespace: string, pod: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_pod_shell", { cluster, namespace, pod }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell into an Incus instance as an embedded terminal session.
 */
async klusterIncusShell(name: string, remote: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kluster_incus_shell", { name, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every background tunnel across all sshm instances (fed by the shared
 * `tunnels/<pid>.json` files), plus a reap of this app's dead children.
 */
async listTunnels() : Promise<TunnelRecord[]> {
    return await TAURI_INVOKE("list_tunnels");
},
/**
 * Saved (persisted) tunnels defined on a host.
 */
async hostTunnels(name: string) : Promise<Tunnel[]> {
    return await TAURI_INVOKE("host_tunnels", { name });
},
/**
 * Start the host's saved tunnel at `index` as a background `ssh -N`.
 */
async startTunnel(hostName: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_tunnel", { hostName, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a background tunnel this app started, by pid.
 */
async stopTunnel(pid: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_tunnel", { pid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force a reload of the DB from disk (e.g. after a live-sync event) and return
 * the fresh host list.
 */
async reloadDb() : Promise<Host[]> {
    return await TAURI_INVOKE("reload_db");
},
/**
 * Open an embedded ssh session to `host_name`. Returns the session id; output
 * then arrives as `TermOutputEvent`s carrying that id. Mosh is rejected (it
 * stays external-terminal only).
 */
async termOpen(hostName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_open", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a local shell (the user's `$SHELL`, else `/bin/sh`) in the app.
 */
async termOpenLocal() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_open_local") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termWrite(id: string, data: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_write", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termResize(id: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_resize", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termClose(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_close", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dbChangedEvent: DbChangedEvent,
termExitEvent: TermExitEvent,
termOutputEvent: TermOutputEvent
}>({
dbChangedEvent: "db-changed-event",
termExitEvent: "term-exit-event",
termOutputEvent: "term-output-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppConfig = { default_port?: number; default_username?: string; default_identity_file?: string; export_path?: string; 
/**
 * Auto-refresh reachability/latency for every host in the background.
 * Enabled by default; user can turn it off from the Settings tab.
 */
auto_health_check?: boolean; 
/**
 * Pause the background health worker while an interactive SSH session
 * is in the foreground, and resume it on return. Avoids the network
 * noise of probing every host while you're actually working on one.
 * Enabled by default; toggle from the Settings tab.
 */
pause_health_on_session?: boolean; 
/**
 * How often (seconds) the background worker re-probes every host.
 * Doubles as the cache TTL — entries older than this are re-probed.
 */
health_ttl_secs?: number; 
/**
 * TCP connect timeout (ms) used by each probe. SSH banner read is
 * derived from this (~1/3, capped at 750ms).
 */
health_probe_timeout_ms?: number; 
/**
 * How often (seconds) the Kluster tab refreshes the docker container
 * list and the pods of every saved cluster.
 */
kluster_refresh_secs?: number; 
/**
 * Default `--tail N` for `docker logs` / `kubectl logs` from the
 * Kluster tab.
 */
kluster_log_tail_lines?: number; 
/**
 * Command prefix used to open an SSH session in a new terminal window
 * (the `o` hotkey). Empty = auto-detect. Example: `kitty -e`,
 * `wezterm start --`, `gnome-terminal --`, `alacritty -e`.
 */
external_terminal?: string; 
/**
 * Emit native desktop notifications (tunnel dropped, host up/down).
 * Enabled by default; toggle from the Settings tab.
 */
notifications_enabled?: boolean; 
/**
 * Custom icon for desktop notifications (path, `~` allowed). Empty = OS
 * default. On macOS this needs `terminal-notifier` installed — plain
 * `osascript` can't override the notification icon.
 */
notification_icon?: string }
/**
 * One saved cluster entry. `kubeconfig` and `context` are both optional;
 * when omitted, `kubectl` is invoked with no `--kubeconfig`/`--context`
 * flags and falls back to the standard env / `current-context` rules.
 */
export type Cluster = { name: string; kind?: ClusterKind; kubeconfig?: string | null; context?: string | null; namespace_default?: string | null }
/**
 * Display flavour for a saved cluster — purely cosmetic, drives the badge in
 * the tab. Detection is naïve (substring on context name), users can toggle.
 */
export type ClusterKind = "K8s" | "K3s"
/**
 * Snapshot of one Docker container at the moment of `docker ps`.
 */
export type ContainerInfo = { id: string; name: string; image: string; status: string; running: boolean }
/**
 * Emitted when a shared config file changes on disk (from this app, the TUI,
 * another GUI instance, or a text editor). The frontend refreshes whichever
 * view the flags indicate. Backed by `sshm_core::watch`.
 */
export type DbChangedEvent = { hosts: boolean; kluster: boolean; settings: boolean }
/**
 * A reference to a remote Docker daemon reached over SSH. The actual
 * connection details are looked up from the saved Host map (`host.json`)
 * at runtime, so renaming/editing the SSH host's user/port flows through.
 */
export type DockerRemote = { 
/**
 * Name of an entry in the SSH Host DB (`Host.name`).
 */
host_alias: string }
/**
 * Représente une entrée d'hôte SSH (schéma v2).
 */
export type Host = { 
/**
 * Alias (clé logique)
 */
name: string; 
/**
 * Hostname ou IP (ex `1.2.3.4` ou `example.com`)
 */
host: string; 
/**
 * Port SSH (par défaut 22)
 */
port?: number; 
/**
 * Nom d'utilisateur SSH
 */
username?: string; 
/**
 * Chemin vers la clé privée (ex: ~/.ssh/id_ed25519)
 */
identity_file?: string | null; 
/**
 * ProxyJump éventuel. Peut être une chaîne multi-hop séparée par des virgules
 * (ex: "bastion1,bastion2"). Chaque entrée peut être un nom d'hôte sauvegardé
 * dans sshm — il sera alors résolu en `user@host:port` au lancement.
 */
proxy_jump?: string | null; 
/**
 * Tags pour filtrage/organisation
 */
tags?: string[] | null; 
/**
 * Folder logique (ex : "Production", "Staging", etc.)
 * Peut être None (pas de dossier)
 */
folder?: string | null; 
/**
 * Timestamp RFC3339 UTC de la dernière connexion réussie.
 */
last_connected_at?: string | null; 
/**
 * Nombre total de connexions depuis ce gestionnaire.
 */
use_count?: number; 
/**
 * Marqueur "favori" (affiché en tête de liste via tri dédié).
 */
favorite?: boolean; 
/**
 * Tunnels persistants associés à cet hôte.
 */
tunnels?: Tunnel[]; 
/**
 * Forward le ssh-agent local (`-A`). Implication de sécurité : permet à un
 * utilisateur root du host distant d'utiliser tes clés. À n'activer que sur
 * des hôtes de confiance (typiquement bastions). Désactivé par défaut.
 */
forward_agent?: boolean; 
/**
 * Connecte via `mosh` plutôt que `ssh`. mosh doit être installé localement
 * et sur l'hôte distant ; le port / l'identité / le ProxyJump sont passés
 * à mosh via `--ssh`. Désactivé par défaut.
 */
mosh?: boolean; 
/**
 * Note libre de l'utilisateur sur cet hôte (affichée dans le panneau de
 * détail). `None` quand aucune note n'a été saisie.
 */
notes?: string | null; 
/**
 * Commande à exécuter automatiquement à la connexion (mappée sur l'option
 * ssh `RemoteCommand`, avec `-t` pour forcer un TTY). Par défaut, la
 * commande est lancée puis on enchaîne sur un shell interactif de login
 * (`; exec $SHELL -l` ajouté automatiquement) — sinon ssh fermerait la
 * session dès la fin de la commande. Si la commande contient `exec `,
 * elle est utilisée telle quelle (l'utilisateur gère le shell lui-même).
 * `None` = shell de login normal. Ignoré en mode mosh.
 */
remote_command?: string | null }
/**
 * One SSH key under `~/.ssh`, with paths flattened to strings for the webview.
 */
export type IdentityDto = { private: string; public: string; key_type: string; bits: number | null; comment: string; fingerprint: string; in_agent: boolean; is_hardware: boolean }
/**
 * Snapshot of one Incus instance (container or VM).
 */
export type IncusInstance = { name: string; 
/**
 * `container` or `virtual-machine`.
 */
kind: string; 
/**
 * `Running`, `Stopped`, …
 */
status: string; 
/**
 * Image alias / fingerprint, when reported.
 */
image: string; running: boolean }
/**
 * A saved cluster/remote plus which runtime it targets, for the Kluster tab.
 */
export type KlusterOverview = { clusters: Cluster[]; incus_remotes: string[]; docker_remotes: DockerRemote[]; docker_local_available: boolean; incus_local_available: boolean; kube_available: boolean }
/**
 * A start / stop / restart operation on a Docker container or Incus instance.
 */
export type LifecycleAction = "Start" | "Stop" | "Restart"
/**
 * Snapshot of one k8s pod at the moment of `kubectl get pods`.
 */
export type PodInfo = { namespace: string; name: string; containers: string[]; 
/**
 * e.g. `Running`, `Pending`, `CrashLoopBackOff`.
 */
phase: string }
/**
 * The embedded terminal session `id`'s child process exited.
 */
export type TermExitEvent = { id: string }
/**
 * A chunk of output bytes from an embedded terminal session `id`.
 */
export type TermOutputEvent = { id: string; data: number[] }
/**
 * Définition d'un tunnel SSH sauvegardable.
 */
export type Tunnel = { 
/**
 * Libellé court (ex : "Postgres prod").
 */
label?: string; kind?: TunnelKind; 
/**
 * Port côté local (Local/Dynamic) ou côté remote-bind (Remote).
 */
local_port: number; 
/**
 * Port distant cible (Local/Remote). Ignoré pour Dynamic.
 */
remote_port?: number; 
/**
 * Hôte distant cible (Local/Remote). Vide => `localhost` côté remote.
 */
remote_host?: string }
/**
 * Type de tunnel SSH.
 */
export type TunnelKind = 
/**
 * `-L` Local forward: localhost:local_port -> remote:remote_port (via SSH host)
 */
"Local" | 
/**
 * `-R` Remote forward: remote:remote_port -> localhost:local_port
 */
"Remote" | 
/**
 * `-D` Dynamic SOCKS proxy on localhost:local_port
 */
"Dynamic"
/**
 * One running background tunnel, as persisted to a per-instance state file.
 * 
 * The field names here are the shared on-disk contract every frontend reads
 * and writes, so a dashboard in one instance can list another's tunnels.
 * `started` is an RFC3339 timestamp (the TUI serializes a `DateTime<Utc>` to
 * the exact same string, so the two interoperate).
 */
export type TunnelRecord = { 
/**
 * PID of the `ssh -N` process.
 */
pid: number; host_name: string; 
/**
 * `user@host:port`, for display.
 */
host_display: string; tunnel: Tunnel; 
/**
 * RFC3339 start timestamp.
 */
started: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
